# Generated by Django 5.0.6 on 2024-06-17 22:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(max_length=10)),
                ('timeframe', models.CharField(max_length=10)),
                ('strategy', models.TextField(default='')),
                ('profit', models.FloatField(default=0)),
                ('profit_percent', models.FloatField(default=0)),
                ('summary', models.TextField(default='')),
                ('strategy_description', models.TextField(default='')),
                ('updated_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
