# Generated by Django 5.2 on 2025-04-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, verbose_name='Symbol')),
                ('from_token', models.CharField(max_length=10, verbose_name='From token')),
                ('to_token', models.CharField(max_length=10, verbose_name='To token')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('month', models.PositiveIntegerField(verbose_name='Month')),
                ('open_time', models.PositiveBigIntegerField(verbose_name='Open unix timestamp')),
                ('timeframe', models.TextField(choices=[('1min', '1min'), ('5min', '5min'), ('15min', '15min'), ('30min', '30min'), ('1h', '1h'), ('4h', '4h'), ('6h', '6h'), ('1d', '1d')], max_length=20, verbose_name='Timeframe')),
                ('open', models.FloatField(verbose_name='Open price')),
                ('high', models.FloatField(verbose_name='High price')),
                ('low', models.FloatField(verbose_name='Low price')),
                ('close', models.FloatField(verbose_name='Close price')),
                ('volume', models.FloatField(verbose_name='Volume')),
            ],
            options={
                'indexes': [models.Index(fields=['year'], name='api_v2_klin_year_c23288_idx'), models.Index(fields=['month'], name='api_v2_klin_month_3836e8_idx'), models.Index(fields=['symbol'], name='api_v2_klin_symbol_1004ca_idx'), models.Index(fields=['timeframe'], name='api_v2_klin_timefra_afa7ed_idx')],
            },
        ),
    ]
